version: '3'

services:
  web:
    build: .
    ports:
    - "80:80"
    - "443:443"
    environment: 
      DATABASE: "mysql://virtualpol:virtualpol@mysql:3306/virtualpol"
      COOKIE_KEY: 123456
      SHA_KEY: 123456
      TZ: "Europe/Madrid"
    links:
      - mysql
    volumes: 
      - ./:/app/
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: virtualpol
      MYSQL_USER: virtualpol
      MYSQL_PASSWORD: virtualpol
      MYSQL_ROOT_PASSWORD: virtualpol
      TZ: "Europe/Madrid"
    ports:
      - "3306:3306"
    restart: always
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password 
volumes:
  db_data: {}
